const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function setup(){const calls=[];const fileApi=new Proxy({}, {get:(_,name)=>options=>calls.push({name,options})});const context={module:{exports:{}},wx:new Proxy({}, {get:(_,name)=>name==='env'?{USER_DATA_PATH:'wxfile://usr'}:name==='getFileSystemManager'?()=>fileApi:options=>calls.push({name,options})})};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../miniprogram/shared/preview-images.js'),'utf8'),context);return {preview:context.module.exports,calls};}
(async()=>{
 const {preview,calls}=setup();const page={_alive:true};const urls=['/album-one/images/a.jpg','/assets/b.jpg'];const pending=preview(page,urls[1],urls);await preview(page,urls[0],urls);assert.equal(calls.filter(c=>c.name==='readFile').length,2);assert(!calls.some(c=>c.name==='previewImage'));
 const reads=calls.filter(c=>c.name==='readFile');const bytesA=new ArrayBuffer(3),bytesB=new ArrayBuffer(5);reads[1].options.success({data:bytesB});reads[0].options.success({data:bytesA});const writes=calls.filter(c=>c.name==='writeFile');assert.equal(writes[0].options.data,bytesB);assert.equal(writes[1].options.data,bytesA);writes.forEach(c=>c.options.success());await pending;const opened=calls.find(c=>c.name==='previewImage').options;assert.equal(opened.current,writes[0].options.filePath);assert.deepEqual([...opened.urls],[writes[1].options.filePath,writes[0].options.filePath]);assert(opened.urls.every(p=>p.startsWith('wxfile://usr/wedding-preview-')));assert.equal(page._previewLoading,false);preview.cleanup(page);assert.equal(calls.filter(c=>c.name==='unlink').length,2);
 const failed=setup();const fp={_alive:true};const f=failed.preview(fp,urls[0],urls);failed.calls.find(c=>c.name==='readFile').options.fail({errMsg:'unavailable'});await f;assert(!failed.calls.some(c=>c.name==='previewImage'));assert(failed.calls.some(c=>c.name==='hideLoading'));assert(failed.calls.some(c=>c.name==='showToast'));assert.equal(fp._previewLoading,false);
 const late=setup();const lp={_alive:true};const l=late.preview(lp,urls[0],[urls[0]]);late.calls.find(c=>c.name==='readFile').options.success({data:bytesA});lp._alive=false;late.preview.cleanup(lp);late.calls.find(c=>c.name==='writeFile').options.success();await l;assert(!late.calls.some(c=>c.name==='previewImage'||c.name==='showToast'));assert(late.calls.some(c=>c.name==='unlink'));
 const remote=setup(),rp={_alive:true},remoteUrls=['https://media.example/one.jpg?sign=a','/assets/local.jpg','https://media.example/two.jpg?sign=b'];
 const mixed=remote.preview(rp,remoteUrls[2],remoteUrls);assert.equal(remote.calls.filter(c=>c.name==='readFile').length,1);remote.calls.find(c=>c.name==='readFile').options.success({data:bytesA});remote.calls.find(c=>c.name==='writeFile').options.success();await mixed;
 const remoteOpened=remote.calls.find(c=>c.name==='previewImage').options;assert.equal(remoteOpened.current,remoteUrls[2]);assert.equal(remoteOpened.urls[0],remoteUrls[0]);assert(remoteOpened.urls[1].startsWith('wxfile://'));assert.equal(remoteOpened.urls[2],remoteUrls[2]);remoteOpened.fail();assert(remote.calls.some(c=>c.name==='showToast'));remote.preview.cleanup(rp);assert.equal(remote.calls.filter(c=>c.name==='unlink').length,1);
 console.log('PASS HTTPS媒体直接交给原生预览，混合本地照片顺序正确、失败可重试且只清理本地副本');
 console.log('PASS 代码包图片转本地媒体、保留字节及选中顺序、重复点击去重、失败可重试、离开后取消并清理副本');
})().catch(error=>{console.error(error);process.exitCode=1;});
